### ISSUE TITLE
Failure tests

### ISSUE THREAD

**Issue by miklblitz** [alejandrobabio/dwr-todo-example#2]
i've cloned repo and installed gems 'bundle install'.
Than have run rspec and got errors:

```
An error occurred while loading ./spec/features/main/complete_task_spec.rb.
Failure/Error: Todo::Container.start :persistence

LoadError:
  cannot load such file -- sequel
# ./system/boot/persistence.rb:5:in `block (2 levels) in <top (required)>'
# ./spec/db_spec_helper.rb:5:in `<top (required)>'
# ./spec/web_spec_helper.rb:3:in `require_relative'
# ./spec/web_spec_helper.rb:3:in `<top (required)>'
# ./spec/features/main/complete_task_spec.rb:3:in `<top (required)>'

An error occurred while loading ./spec/features/main/create_task_spec.rb.
Failure/Error: Todo::Container.start :persistence

LoadError:
  cannot load such file -- sequel
# ./system/boot/persistence.rb:5:in `block (2 levels) in <top (required)>'
# ./spec/db_spec_helper.rb:5:in `<top (required)>'
# ./spec/web_spec_helper.rb:3:in `require_relative'
# ./spec/web_spec_helper.rb:3:in `<top (required)>'
# ./spec/features/main/create_task_spec.rb:3:in `<top (required)>'
```
etc

google did not help me. My assusmes - **my ruby version 2.5.1**

**Comment by alejandrobabio** [comment]
@miklblitz It is failing in `require 'sequel'`. So it seems that the gem sequel was not installed correctly, or it's not in the path. If you are using rbenv perhaps you need to run `rbenv rehash`. Or, run `bundle show sequel` to see the gem path.

BTW, I installed ruby-2.5.1 and it works fine in my environment. Following the steps that you did, it is needed to create the DB and migrate it before running the specs. In the step-by-step guide, you will find how to create and migrate the test DB.

**Comment by miklblitz** [comment]
thanks
